# Generated by Django 6.0 on 2025-12-12 06:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_id', models.CharField(max_length=50, unique=True)),
                ('record_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('class_name', models.CharField(max_length=200)),
                ('photo', models.URLField()),
                ('device_photos', models.JSONField(default=list)),
                ('device_description', models.TextField()),
                ('check_in_time', models.DateTimeField(auto_now_add=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('checked-in', 'Checked In'), ('checked-out', 'Checked Out')], default='checked-in', max_length=20)),
            ],
        ),
    ]
