# Generated by Django 6.0 on 2025-12-12 15:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='record_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
